import { db } from "@/db";
import { aidPrograms } from "@/db/schema";
import { eq } from "drizzle-orm";

export async function seedAidPrograms() {
  // Check if already seeded
  const existing = await db.select().from(aidPrograms).limit(1);
  if (existing.length > 0) return;

  const programs = [
    {
      name: "STR (Sumbangan Tunai Rahmah)",
      nameMs: "STR (Sumbangan Tunai Rahmah)",
      description: "Cash aid for B40 & lower M40 households. Up to RM2,500/year. Paid in 4 phases.",
      descriptionMs: "Bantuan tunai untuk isi rumah B40 & M40 rendah. Sehingga RM2,500/tahun. Dibayar 4 fasa.",
      category: "cash",
      state: null,
      incomeMin: 0,
      incomeMax: 5000,
      dependentsMin: 1,
      studentRequired: false,
      vehicleType: null,
      elderlyRequired: false,
      okuRequired: false,
      singleParentRequired: false,
      monthlySavings: 208,
      documents: ["MyKad (IC)", "Bank account statement", "Latest payslip", "Marriage cert (if married)"],
      documentsMs: ["MyKad", "Penyata bank", "Slip gaji terkini", "Sijil kahwin (jika berkahwin)"],
      deadline: new Date("2026-12-31"),
      applicationLink: "https://bantuantunai.hasil.gov.my",
      status: "active",
    },
    {
      name: "SARA Food Assistance",
      nameMs: "Bantuan Makanan SARA",
      description: "Monthly food credit via MyKad for B40 single adults & households. RM50-RM100/month at selected stores.",
      descriptionMs: "Kredit makanan bulanan guna MyKad untuk B40 bujang & isi rumah. RM50-RM100/bulan di kedai terpilih.",
      category: "subsidy",
      state: null,
      incomeMin: 0,
      incomeMax: 2500,
      dependentsMin: 0,
      studentRequired: false,
      vehicleType: null,
      elderlyRequired: false,
      okuRequired: false,
      singleParentRequired: false,
      monthlySavings: 75,
      documents: ["MyKad (IC)", "Latest payslip", "Bank account statement"],
      documentsMs: ["MyKad", "Slip gaji terkini", "Penyata bank"],
      deadline: new Date("2026-12-31"),
      applicationLink: "https://mykasih.com.my",
      status: "active",
    },
    {
      name: "Bantuan Kanak-Kanak JKM",
      nameMs: "Bantuan Kanak-Kanak JKM",
      description: "Monthly welfare aid for poor families with children under 18. Up to RM200/child (max RM1,000/family).",
      descriptionMs: "Bantuan bulanan keluarga miskin ada anak bawah 18 tahun. Sehingga RM200/anak (max RM1,000/keluarga).",
      category: "welfare",
      state: null,
      incomeMin: 0,
      incomeMax: 1500,
      dependentsMin: 1,
      studentRequired: false,
      vehicleType: null,
      elderlyRequired: false,
      okuRequired: false,
      singleParentRequired: false,
      monthlySavings: 200,
      documents: ["MyKad (IC)", "Children's birth certs", "Latest payslip", "Bank statement", "JKM form"],
      documentsMs: ["MyKad", "Sijil lahir anak-anak", "Slip gaji terkini", "Penyata bank", "Borang JKM"],
      deadline: new Date("2026-12-31"),
      applicationLink: "https://www.jkm.gov.my",
      status: "active",
    },
    {
      name: "Bantuan OKU",
      nameMs: "Bantuan OKU",
      description: "Monthly allowance for persons with disabilities. RM300-RM500/month depending on category.",
      descriptionMs: "Elaun bulanan untuk orang kurang upaya. RM300-RM500/bulan ikut kategori.",
      category: "welfare",
      state: null,
      incomeMin: 0,
      incomeMax: 3000,
      dependentsMin: 0,
      studentRequired: false,
      vehicleType: null,
      elderlyRequired: false,
      okuRequired: true,
      singleParentRequired: false,
      monthlySavings: 400,
      documents: ["MyKad (IC)", "OKU Card", "Latest payslip", "Bank statement", "Medical report"],
      documentsMs: ["MyKad", "Kad OKU", "Slip gaji terkini", "Penyata bank", "Laporan perubatan"],
      deadline: new Date("2026-12-31"),
      applicationLink: "https://www.jkm.gov.my",
      status: "active",
    },
    {
      name: "Bantuan Warga Emas",
      nameMs: "Bantuan Warga Emas",
      description: "Monthly aid for elderly (60+) below poverty line. RM500/month.",
      descriptionMs: "Bantuan bulanan warga emas (60+) bawah garis kemiskinan. RM500/bulan.",
      category: "welfare",
      state: null,
      incomeMin: 0,
      incomeMax: 1500,
      dependentsMin: 0,
      studentRequired: false,
      vehicleType: null,
      elderlyRequired: true,
      okuRequired: false,
      singleParentRequired: false,
      monthlySavings: 500,
      documents: ["MyKad (IC)", "Latest payslip / no-income declaration", "Bank statement"],
      documentsMs: ["MyKad", "Slip gaji / surat akuan tiada pendapatan", "Penyata bank"],
      deadline: new Date("2026-12-31"),
      applicationLink: "https://www.jkm.gov.my",
      status: "active",
    },
    {
      name: "Bantuan Ibu Tunggal",
      nameMs: "Bantuan Ibu Tunggal",
      description: "Support for single mothers: RM300/month + entrepreneurship training.",
      descriptionMs: "Sokongan ibu tunggal: RM300/bulan + latihan keusahawanan.",
      category: "welfare",
      state: null,
      incomeMin: 0,
      incomeMax: 3000,
      dependentsMin: 1,
      studentRequired: false,
      vehicleType: null,
      elderlyRequired: false,
      okuRequired: false,
      singleParentRequired: true,
      monthlySavings: 300,
      documents: ["MyKad (IC)", "Children's birth certs", "Divorce/death cert of spouse", "Latest payslip"],
      documentsMs: ["MyKad", "Sijil lahir anak", "Sijil cerai/kematian pasangan", "Slip gaji terkini"],
      deadline: new Date("2026-12-31"),
      applicationLink: "https://www.jkm.gov.my",
      status: "active",
    },
    {
      name: "Bantuan Awal Persekolahan (Back to School)",
      nameMs: "Bantuan Awal Persekolahan",
      description: "One-off school aid. RM150/student for Year 1 to Form 5. Usually paid before school year starts.",
      descriptionMs: "Bantuan persekolahan one-off. RM150/pelajar Darjah 1 hingga Tingkatan 5. Biasanya sebelum tahun baru sekolah.",
      category: "education",
      state: null,
      incomeMin: 0,
      incomeMax: 5000,
      dependentsMin: 1,
      studentRequired: true,
      vehicleType: null,
      elderlyRequired: false,
      okuRequired: false,
      singleParentRequired: false,
      monthlySavings: 0,
      documents: ["MyKad parent (IC)", "Child's MyKad / birth cert", "School confirmation letter"],
      documentsMs: ["MyKad ibu bapa", "MyKad / sijil lahir anak", "Surat pengesahan sekolah"],
      deadline: new Date("2026-03-15"),
      applicationLink: "https://www.moe.gov.my",
      status: "active",
    },
    {
      name: "Bantuan KIP (Kad Insentif Pelajar)",
      nameMs: "Bantuan KIP (Kad Insentif Pelajar)",
      description: "RM200/month education incentive for IPT students from B40 families.",
      descriptionMs: "Insentif pendidikan RM200/bulan untuk pelajar IPT dari keluarga B40.",
      category: "education",
      state: null,
      incomeMin: 0,
      incomeMax: 4000,
      dependentsMin: 1,
      studentRequired: true,
      vehicleType: null,
      elderlyRequired: false,
      okuRequired: false,
      singleParentRequired: false,
      monthlySavings: 200,
      documents: ["MyKad (IC)", "University acceptance letter", "Parents' payslip", "Bank statement"],
      documentsMs: ["MyKad", "Surat tawaran universiti", "Slip gaji ibu bapa", "Penyata bank"],
      deadline: new Date("2026-06-30"),
      applicationLink: "https://www.mohe.gov.my",
      status: "active",
    },
    {
      name: "Bantuan Subsidi Petrol (BUDI Madani)",
      nameMs: "Bantuan Subsidi Petrol (BUDI Madani)",
      description: "Targeted fuel subsidy: RM200/month for diesel & RON95. For B40 & M40 eligible vehicle owners.",
      descriptionMs: "Subsidi petrol bersasar: RM200/bulan untuk diesel & RON95. Untuk pemilik kenderaan B40 & M40.",
      category: "subsidy",
      state: null,
      incomeMin: 0,
      incomeMax: 5000,
      dependentsMin: 0,
      studentRequired: false,
      vehicleType: "car",
      elderlyRequired: false,
      okuRequired: false,
      singleParentRequired: false,
      monthlySavings: 200,
      documents: ["MyKad (IC)", "Vehicle grant (geran)", "Latest payslip", "Bank statement"],
      documentsMs: ["MyKad", "Geran kenderaan", "Slip gaji terkini", "Penyata bank"],
      deadline: new Date("2026-12-31"),
      applicationLink: "https://budimadani.gov.my",
      status: "active",
    },
    {
      name: "e-Kasih Registration",
      nameMs: "Pendaftaran e-Kasih",
      description: "National poverty database. Register to qualify for multiple aid programs automatically.",
      descriptionMs: "Pangkalan data kemiskinan nasional. Daftar untuk layak pelbagai bantuan secara automatik.",
      category: "welfare",
      state: null,
      incomeMin: 0,
      incomeMax: 1500,
      dependentsMin: 0,
      studentRequired: false,
      vehicleType: null,
      elderlyRequired: false,
      okuRequired: false,
      singleParentRequired: false,
      monthlySavings: 0,
      documents: ["MyKad (IC)", "Latest payslip / no-income declaration", "Utility bills", "Household info form"],
      documentsMs: ["MyKad", "Slip gaji / surat akuan tiada pendapatan", "Bil utiliti", "Borang maklumat isi rumah"],
      deadline: new Date("2026-12-31"),
      applicationLink: "https://ekasih.icu.gov.my",
      status: "active",
    },
    // State-specific programs
    {
      name: "Bantuan Kehidupan Sejahtera Selangor (BINGKAS)",
      nameMs: "Bantuan Kehidupan Sejahtera Selangor (BINGKAS)",
      description: "Selangor state welfare: RM300/month for eligible families. Covers basic needs.",
      descriptionMs: "Bantuan kebajikan negeri Selangor: RM300/bulan untuk keluarga layak. Meliputi keperluan asas.",
      category: "state",
      state: "Selangor",
      incomeMin: 0,
      incomeMax: 3000,
      dependentsMin: 1,
      studentRequired: false,
      vehicleType: null,
      elderlyRequired: false,
      okuRequired: false,
      singleParentRequired: false,
      monthlySavings: 300,
      documents: ["MyKad (IC)", "Proof of Selangor residency", "Latest payslip", "Bank statement"],
      documentsMs: ["MyKad", "Bukti bermastautin Selangor", "Slip gaji terkini", "Penyata bank"],
      deadline: new Date("2026-12-31"),
      applicationLink: "https://www.selangor.gov.my",
      status: "active",
    },
    {
      name: "i-Suri EPF",
      nameMs: "i-Suri EPF",
      description: "EPF incentive for housewives: govt contributes RM480/year to your EPF account.",
      descriptionMs: "Insentif KWSP suri rumah: kerajaan sumbang RM480/tahun ke akaun KWSP anda.",
      category: "welfare",
      state: null,
      incomeMin: 0,
      incomeMax: 4000,
      dependentsMin: 1,
      studentRequired: false,
      vehicleType: null,
      elderlyRequired: false,
      okuRequired: false,
      singleParentRequired: false,
      monthlySavings: 40,
      documents: ["MyKad (IC)", "Husband's payslip", "Marriage cert", "EPF statement"],
      documentsMs: ["MyKad", "Slip gaji suami", "Sijil kahwin", "Penyata KWSP"],
      deadline: new Date("2026-12-31"),
      applicationLink: "https://www.kwsp.gov.my",
      status: "active",
    },
    {
      name: "Program Perumahan Rakyat (PPR)",
      nameMs: "Program Perumahan Rakyat (PPR)",
      description: "Affordable housing for low-income families. Rent from RM124/month in major cities.",
      descriptionMs: "Rumah mampu milik keluarga berpendapatan rendah. Sewa dari RM124/bulan di bandar utama.",
      category: "subsidy",
      state: null,
      incomeMin: 0,
      incomeMax: 3000,
      dependentsMin: 1,
      studentRequired: false,
      vehicleType: null,
      elderlyRequired: false,
      okuRequired: false,
      singleParentRequired: false,
      monthlySavings: 500,
      documents: ["MyKad (IC)", "Latest payslip (3 months)", "Marriage cert (if applicable)", "Bank statement"],
      documentsMs: ["MyKad", "Slip gaji (3 bulan)", "Sijil kahwin (jika berkaitan)", "Penyata bank"],
      deadline: new Date("2026-12-31"),
      applicationLink: "https://www.kpkt.gov.my",
      status: "active",
    },
    {
      name: "Bantuan Am JKM",
      nameMs: "Bantuan Am JKM",
      description: "General welfare assistance for those in crisis. One-off or monthly. Amount varies by case.",
      descriptionMs: "Bantuan kebajikan am untuk mereka dalam krisis. One-off atau bulanan. Jumlah ikut kes.",
      category: "welfare",
      state: null,
      incomeMin: 0,
      incomeMax: 2000,
      dependentsMin: 0,
      studentRequired: false,
      vehicleType: null,
      elderlyRequired: false,
      okuRequired: false,
      singleParentRequired: false,
      monthlySavings: 350,
      documents: ["MyKad (IC)", "Latest payslip", "Supporting docs (medical bill, etc)", "JKM form"],
      documentsMs: ["MyKad", "Slip gaji terkini", "Dokumen sokongan (bil perubatan dll)", "Borang JKM"],
      deadline: new Date("2026-12-31"),
      applicationLink: "https://www.jkm.gov.my",
      status: "active",
    },
    {
      name: "MySalam Health Protection",
      nameMs: "Perlindungan Kesihatan MySalam",
      description: "Free takaful for B40: RM8,000 critical illness + RM50/day hospital income replacement.",
      descriptionMs: "Takaful percuma B40: RM8,000 penyakit kritikal + RM50/hari gantian pendapatan hospital.",
      category: "health",
      state: null,
      incomeMin: 0,
      incomeMax: 5000,
      dependentsMin: 0,
      studentRequired: false,
      vehicleType: null,
      elderlyRequired: false,
      okuRequired: false,
      singleParentRequired: false,
      monthlySavings: 0,
      documents: ["MyKad (IC)", "Latest payslip", "Bank statement"],
      documentsMs: ["MyKad", "Slip gaji terkini", "Penyata bank"],
      deadline: new Date("2026-12-31"),
      applicationLink: "https://www.mysalam.com.my",
      status: "active",
    },
  ];

  for (const p of programs) {
    await db.insert(aidPrograms).values(p as any);
  }

  console.log(`Seeded ${programs.length} aid programs`);
}
