import { NewAidProgram } from './schema';

export const INITIAL_AID_PROGRAMS: NewAidProgram[] = [
  {
    code: 'STR_2026',
    name: 'Sumbangan Tunai Rahmah (STR 2026)',
    category: 'Bantuan Tunai',
    provider: 'Kementerian Kewangan (MOF) / LHDNM',
    descriptionBm: 'Bantuan tunai langsung utama kerajaan persekutuan untuk isi rumah B40 dan M40 bawah serta individu bujang. Bayaran disalurkan berperingkat dalam 4 fasa setahun untuk meringankan kos sara hidup.',
    descriptionEn: 'The flagship federal direct cash assistance program for B40 & lower M40 households and single individuals. Disbursed in 4 phases annually to alleviate cost-of-living burdens.',
    maxIncome: 5000,
    minAge: 21,
    maxAge: 150,
    states: 'ALL',
    targetCategories: 'B40,M40,Warga Emas,Ibu Tunggal,OKU,Belia,ALL',
    amountMin: 500,
    amountMax: 3700,
    frequency: 'Tahunan (4 Fasa)',
    payoutSchedule: 'Fasa 1: Feb 2026 | Fasa 2: Apr 2026 | Fasa 3: Ogo 2026 | Fasa 4: Nov 2026',
    requiredDocs: 'Salinan MyKad Pemohon & Pasangan|Salinan Sijil Lahir Anak/Tanggungan|Penyata Akaun Bank Aktif|Slip Gaji / Pengesahan Pendapatan Terkini',
    applyUrl: 'https://bantuantunai.hasil.gov.my',
    isActive: true,
  },
  {
    code: 'SARA_2026',
    name: 'Sumbangan Asas Rahmah (SARA 2026)',
    category: 'Barangan Asas',
    provider: 'Kementerian Kewangan / MyKasih Foundation',
    descriptionBm: 'Bantuan tanpa tunai (cashless) bernilai RM100 sebulan (RM1,200 setahun) dikreditkan ke MyKad penerima STR yang berdaftar dalam e-Kasih atau berpendapatan rendah untuk pembelian barang dapur di pasar raya dan kedai runcit terpilih.',
    descriptionEn: 'Monthly cashless grocery subsidy of RM100/month (RM1,200/year) credited directly into the MyKad of STR recipients registered in e-Kasih or low-income tiers for basic groceries.',
    maxIncome: 3000,
    minAge: 21,
    maxAge: 150,
    states: 'ALL',
    targetCategories: 'B40,Miskin Tegar,Warga Emas,Ibu Tunggal,OKU,ALL',
    amountMin: 600,
    amountMax: 1200,
    frequency: 'Bulanan (RM100/bln)',
    payoutSchedule: 'Dinkreditkan setiap 1 haribulan (Jan - Dis 2026)',
    requiredDocs: 'Kelulusan STR 2026|Pendaftaran pangkalan data e-Kasih / ICU JPM|MyKad yang sah',
    applyUrl: 'https://www.mykasih.com.my',
    isActive: true,
  },
  {
    code: 'JKM_BWE',
    name: 'Bantuan Warga Emas (BWE JKM)',
    category: 'Kebajikan & OKU',
    provider: 'Jabatan Kebajikan Masyarakat (JKM)',
    descriptionBm: 'Bantuan kewangan bulanan RM500 kepada warga emas (berumur 60 tahun ke atas) yang memerlukan bagi kelangsungan dan kesejahteraan hidup di dalam komuniti.',
    descriptionEn: 'Monthly financial assistance of RM500 for senior citizens (aged 60 and above) in need to ensure basic survival and well-being within the community.',
    maxIncome: 1500,
    minAge: 60,
    maxAge: 150,
    states: 'ALL',
    targetCategories: 'Warga Emas,B40',
    amountMin: 6000,
    amountMax: 6000,
    frequency: 'Bulanan (RM500/bln)',
    payoutSchedule: '1hb - 10hb setiap bulan',
    requiredDocs: 'Salinan MyKad Pemohon|Salinan Bil Air / Elektrik Tempat Tinggal|Penyata Bank Pemohon|Laporan Perubatan (jika berkaitan)',
    applyUrl: 'https://ebantuanjkm.jkm.gov.my',
    isActive: true,
  },
  {
    code: 'JKM_BTB',
    name: 'Bantuan OKU Tidak Berupaya Bekerja (BTB JKM)',
    category: 'Kebajikan & OKU',
    provider: 'Jabatan Kebajikan Masyarakat (JKM)',
    descriptionBm: 'Bantuan kewangan RM300 sebulan kepada Orang Kurang Upaya (OKU) yang tidak berupaya bekerja bagi menyokong keperluan asas harian dan mengurangkan beban penjaga.',
    descriptionEn: 'Monthly allowance of RM300 for Persons with Disabilities (OKU) who are unable to work, supporting daily living needs and easing caregiver burdens.',
    maxIncome: 2500,
    minAge: 16,
    maxAge: 150,
    states: 'ALL',
    targetCategories: 'OKU,B40',
    amountMin: 3600,
    amountMax: 3600,
    frequency: 'Bulanan (RM300/bln)',
    payoutSchedule: '1hb - 10hb setiap bulan',
    requiredDocs: 'Salinan Kad OKU JKM|Salinan MyKad|Surat Pengesahan Pegawai Perubatan / Hospital Kerajaan|Penyata Akaun Bank',
    applyUrl: 'https://ebantuanjkm.jkm.gov.my',
    isActive: true,
  },
  {
    code: 'BINGKAS_SEL',
    name: 'Bantuan Kehidupan Sejahtera Selangor (BINGKAS)',
    category: 'Barangan Asas',
    provider: 'Kerajaan Negeri Selangor / Selgate',
    descriptionBm: 'Bantuan e-dompet bulanan RM300 (RM3,600 setahun) melalui aplikasi Langkah Masuk Dengan Selamat (SELangkah) kepada keluarga berpendapatan bawah RM5,000 yang mempunyai tanggungan di negeri Selangor.',
    descriptionEn: 'Monthly e-wallet allowance of RM300 (RM3,600/year) via the SELangkah app for families earning below RM5,000 with dependents residing in Selangor.',
    maxIncome: 5000,
    minAge: 18,
    maxAge: 150,
    states: 'Selangor',
    targetCategories: 'B40,M40,Ibu Tunggal,ALL',
    amountMin: 3600,
    amountMax: 3600,
    frequency: 'Bulanan (RM300/bln e-wallet)',
    payoutSchedule: 'Dikreditkan ke aplikasi SELangkah pada 1hb setiap bulan',
    requiredDocs: 'Salinan MyKad Pemohon & Pasangan|Sijil Lahir Anak di bawah 18 tahun|Bukti MASTASTAUTIN / Pengundi Selangor|Slip Gaji / EA Form / Pengesahan Pendapatan',
    applyUrl: 'https://www.bingkasselangor.com',
    isActive: true,
  },
  {
    code: 'MYSALAM_2026',
    name: 'Skim Perlindungan Nasional MySalam',
    category: 'Kesihatan',
    provider: 'Great Eastern / Kementerian Kewangan',
    descriptionBm: 'Skim perlindungan takaful kesihatan percuma untuk golongan B40 yang memberi elaun kemasukan hospital RM50/hari (sehingga RM700 setahun) dan pampasan penyakit kritikal RM8,000.',
    descriptionEn: 'Free national health takaful protection for B40 recipients providing hospitalization allowance of RM50/day (up to RM700/year) and an RM8,000 critical illness payout.',
    maxIncome: 4000,
    minAge: 18,
    maxAge: 65,
    states: 'ALL',
    targetCategories: 'B40,ALL',
    amountMin: 700,
    amountMax: 8700,
    frequency: 'Sekali Bayar / Tuntutan Hospital',
    payoutSchedule: 'Tuntutan diproses dalam 14 hari bekerja selepas dokumen lengkap dihantar',
    requiredDocs: 'Salinan MyKad|Nota Discaj Hospital Kerajaan / Surat Pengesahan Doktor|Penyata Bank Aktif',
    applyUrl: 'https://www.mysalam.com.my',
    isActive: true,
  },
  {
    code: 'PEKA_B40',
    name: 'Skim Peduli Kesihatan untuk Kumpulan B40 (PeKa B40)',
    category: 'Kesihatan',
    provider: 'ProtectHealth Malaysia / KKM',
    descriptionBm: 'Saringan kesihatan percuma di klinik swasta & kerajaan, bantuan alat perubatan sehingga RM20,000 (stent, sendi palsu, alat bantu pendengaran), insentif melengkapkan rawatan kanser RM1,000, dan insentif tambang pengangkutan.',
    descriptionEn: 'Free comprehensive health screenings, medical device aid up to RM20,000 (stents, implants, hearing aids), cancer treatment completion incentive RM1,000, and transport allowances.',
    maxIncome: 4800,
    minAge: 40,
    maxAge: 150,
    states: 'ALL',
    targetCategories: 'B40,Warga Emas,ALL',
    amountMin: 500,
    amountMax: 20000,
    frequency: 'Manfaat Saringan & Alat Perubatan',
    payoutSchedule: 'Boleh diakses sepanjang tahun 2026 di klinik berdaftar PeKa B40',
    requiredDocs: 'MyKad Sahaja (Semakan status secara automatik melalui data STR)',
    applyUrl: 'https://pekab40.com.my',
    isActive: true,
  },
  {
    code: 'BAP_2026',
    name: 'Bantuan Awal Persekolahan (BAP 2026)',
    category: 'Pendidikan',
    provider: 'Kementerian Pendidikan Malaysia (KPM)',
    descriptionBm: 'Bantuan kewangan RM150 secara tunai atau kredit ke akaun bagi setiap murid Tahun 1 hingga Tingkatan 5 dari keluarga berpendapatan bawah RM3,000 bagi persediaan sesi persekolahan.',
    descriptionEn: 'Financial assistance of RM150 per student (Standard 1 to Form 5) for households earning below RM3,000 to assist with back-to-school preparations.',
    maxIncome: 3000,
    minAge: 6,
    maxAge: 18,
    states: 'ALL',
    targetCategories: 'B40,Belia,ALL',
    amountMin: 150,
    amountMax: 750,
    frequency: 'Sekali Bayar (Tahunan)',
    payoutSchedule: 'Awal Sesi Persekolahan (Januari - Mac 2026)',
    requiredDocs: 'MyKid / Sijil Lahir Murid|Slip Gaji / Pengesahan Pendapatan Ibu Bapa|Borang Permohonan Sekolah',
    applyUrl: 'https://www.moe.gov.my',
    isActive: true,
  },
  {
    code: 'ZAKAT_ASNAF',
    name: 'Bantuan Kewangan Bulanan Zakat Negeri (Asnaf Fakir Miskin)',
    category: 'Zakat',
    provider: 'Lembaga Zakat Negeri (MAIK / LZS / MAIWP / MAINS)',
    descriptionBm: 'Bantuan kewangan, sewaan rumah, dan makanan asas bulanan oleh pusat pungutan zakat negeri untuk asnaf fakir dan miskin mengikut had kifayah isi rumah.',
    descriptionEn: 'Monthly financial allowance, rental aid, and food support provided by state zakat boards for fakir and miskin asnaf families based on Had Kifayah calculation.',
    maxIncome: 3500,
    minAge: 18,
    maxAge: 150,
    states: 'ALL',
    targetCategories: 'B40,Miskin Tegar,Ibu Tunggal,OKU,Warga Emas,ALL',
    amountMin: 1200,
    amountMax: 6000,
    frequency: 'Bulanan',
    payoutSchedule: 'Disalurkan pertengahan bulan (15hb - 25hb setiap bulan)',
    requiredDocs: 'Salinan MyKad Seluruh Isi Rumah|Surat Pengesahan Mastautin dari Imam Masjid / JPKK|Slip Gaji / Pengesahan Tidak Bekerja|Salinan Kad Nikah / Cerai / Sijil Kematian',
    applyUrl: 'https://www.maiwp.gov.my',
    isActive: true,
  },
  {
    code: 'PTWN_JOHOR',
    name: 'Bantuan Kasih Bangsa Johor (BKBJ)',
    category: 'Bantuan Tunai',
    provider: 'Kerajaan Negeri Johor',
    descriptionBm: 'Inisiatif bantuan kewangan khas dari Kerajaan Negeri Johor untuk golongan B40 Johor, warga emas, dan pelajar kolej/universiti anak Johor.',
    descriptionEn: 'Special state cash assistance initiative by the Johor State Government targeting B40 families, seniors, and higher-ed students residing in Johor.',
    maxIncome: 4500,
    minAge: 18,
    maxAge: 150,
    states: 'Johor',
    targetCategories: 'B40,Belia,Warga Emas,ALL',
    amountMin: 300,
    amountMax: 1000,
    frequency: 'Sekali Bayar / Tahunan',
    payoutSchedule: 'Fasa Pengagihan Mac & September 2026',
    requiredDocs: 'MyKad beralamat Johor / Bukti Mastautin Johor > 5 tahun|Penyata Pendapatan',
    applyUrl: 'https://www.johor.gov.my',
    isActive: true,
  }
];
